# Generated by Django 4.0.3 on 2022-03-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=30, unique=True)),
                ('brand', models.CharField(default='', max_length=40, verbose_name='The brand of the car.')),
                ('modeel', models.CharField(max_length=40, verbose_name='The model of the car.')),
                ('weight', models.CharField(help_text='Weight of the Car.', max_length=30)),
                ('cs', models.CharField(default='', max_length=30, verbose_name='Car Seats')),
                ('cd', models.CharField(default='', max_length=30, verbose_name='Car Doors')),
                ('fueltype', models.CharField(default='', max_length=30)),
                ('fueltankcapacity', models.CharField(default='', max_length=30)),
                ('pyy', models.CharField(default='', help_text='Production Year', max_length=30)),
                ('rd', models.DateField(default='', verbose_name='registration date')),
                ('en', models.CharField(default='', help_text='Engine Number', max_length=30, unique=True)),
                ('cn', models.CharField(default='', max_length=30, verbose_name='Chassis Number')),
                ('color', models.CharField(default='', max_length=30)),
                ('transmissiontype', models.CharField(default='', max_length=30)),
                ('nog', models.CharField(default='', help_text='Number Of Gears', max_length=30)),
                ('maxspeed', models.CharField(default='', max_length=30)),
                ('enginedisplacement', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the driver.', max_length=50)),
                ('code', models.CharField(help_text='The Secret Code.', max_length=50, unique=True)),
                ('bd', models.DateField(verbose_name='birth date')),
                ('sex', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofv', models.CharField(default='', help_text='Type Of Violations.', max_length=50)),
                ('datev', models.DateField(default='', verbose_name='Violation date')),
                ('fee', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruun.car')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.DateField(default='', help_text='registration Date')),
                ('fd', models.DateField(default='', help_text='finished Date')),
                ('city', models.CharField(default='', max_length=30)),
                ('typeoflicense', models.CharField(default='', max_length=30)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruun.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofi', models.CharField(default='', help_text='Type Of Insurance.', max_length=50)),
                ('noi', models.CharField(default='', help_text='Number Of Insurance', max_length=30)),
                ('dateofrenewal', models.DateField(default='', verbose_name='Renewal date')),
                ('dateofexpired', models.DateField(default='', verbose_name='Experation date')),
                ('renewalfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruun.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruun.driver'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruun.driver')),
            ],
        ),
    ]
