# Generated by Django 4.0.3 on 2022-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='nationality',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='nationalnum',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='violations',
            name='vionum',
            field=models.CharField(default='', max_length=30),
        ),
    ]
