# Generated by Django 4.0.3 on 2022-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0002_driver_nationality_driver_nationalnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='Bpay',
            field=models.CharField(default='', help_text='Born Place and Year', max_length=30),
        ),
        migrations.AddField(
            model_name='license',
            name='bloadtype',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='license',
            name='licensenum',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='license',
            name='namee',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='license',
            name='nationalitty',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='license',
            name='nationalnuum',
            field=models.CharField(default='', max_length=30),
        ),
    ]
