# Generated by Django 4.0.3 on 2022-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0003_license_bpay_license_bloadtype_license_licensenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='violnum',
            field=models.CharField(default='', max_length=30),
        ),
    ]
