# Generated by Django 4.0.3 on 2022-05-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0005_driver_carnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(help_text='The Secret Code.', max_length=50),
        ),
    ]
