# Generated by Django 4.0.3 on 2022-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0011_driver_baalance_delete_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.URLField(default=''),
        ),
    ]
