# Generated by Django 4.0.3 on 2022-05-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0012_driver_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='code',
            new_name='driver',
        ),
    ]
