# Generated by Django 4.0.3 on 2022-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0013_rename_code_license_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='iid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
