# Generated by Django 4.0.3 on 2022-05-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0014_driver_iid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='iid',
        ),
    ]
