# Generated by Django 4.0.3 on 2022-05-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0020_mmm_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violations',
            name='plate',
        ),
    ]
