# Generated by Django 4.0.3 on 2022-05-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0022_violations_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='license',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.RemoveField(
            model_name='violations',
            name='user',
        ),
    ]
