# Generated by Django 4.0.3 on 2022-05-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ruun', '0023_remove_car_user_remove_insurance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
