# Generated by Django 4.0.3 on 2022-05-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0024_license_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
    ]
