# Generated by Django 4.0.3 on 2022-05-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0027_remove_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ruun.car'),
        ),
    ]
