# Generated by Django 4.0.3 on 2022-05-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0028_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='plate',
        ),
        migrations.AddField(
            model_name='license',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ruun.driver'),
        ),
    ]
