# Generated by Django 4.0.3 on 2022-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0030_license_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='violations',
            name='IsPaid',
            field=models.BooleanField(default=False),
        ),
    ]
