# Generated by Django 4.0.3 on 2022-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruun', '0031_violations_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='IsPaid',
            field=models.BooleanField(default=False),
        ),
    ]
